[workspace]
resolver = "3"
members = ["wslpluginapi-sys", "xtask"]
default-members = ["wslpluginapi-sys"]


[workspace.package]
version = "0.3.0+2.9.3"
edition = "2021"
readme = "README.md"
authors = ["Mickaël Véril <mika.veril@wanadoo.fr>"]
description = "Rust bindings for the WSL Plugin API"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/mveril/wslpluginapi-sys"
