[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
cargo_metadata = "0.19"
reqwest = { version = "0.12", features = ["blocking"] }
tempfile = "3.19.1"
zip = "2.6.1"
fs_extra = "1.3.0"
