[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", default-features = false, features = ["now"] }
clap = { version = "4.0", features = ["derive"] }
cargo_metadata = "0.19"
reqwest = { version = "0.12", features = ["blocking"] }
tempfile = "3.19.1"
zip = "2.6.1"
serde = { version = "1.0.219", features = ["derive"] }
serde-xml-rs = "0.7.0"
spdx = { version = "0.10.8", features = ["text"] }
log = "0.4.27"
env_logger = "0.11.8"
clap-verbosity-flag = "3.0.2"
anyhow = "1.0.98"
regex = { version = "1.11.1", features = ["use_std"] }
thiserror = "2.0"
markdown-builder = "1.0.0"
walkdir = "2.5.0"
