name: Tag on Merge to Master

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  create-tag:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/') }}
    runs-on: windows-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Version from Branch Name
        id: extract_version
        shell: pwsh
        run: |
          $branchName = "${{ github.event.pull_request.head.ref }}"
          $version = $branchName -replace '^release/', ''
          Write-Host "Extracted version: $version"
          echo "version=$version" >> $env:GITHUB_ENV

      - name: Create Git Tag
        id: create_tag
        shell: pwsh
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "v${{ env.version }}" -a -m "Release version $env:version"
          git push origin "v${{ env.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
